"""Structured artifacts produced by evolution experiments.

Evolution experiments should not edit ``tau2/harness/*.py`` directly.  They
produce JSON artifacts containing learned skills, and evaluation loads those
artifacts as an extension to the static H5 skill library.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Literal


ArtifactMode = Literal["serial", "cross_instance", "debate", "mad", "manual"]


@dataclass
class EvolvedSkill:
    """A learned H5 skill generated by an evolution experiment."""

    id: str
    title: str
    pattern: str
    tip: str
    source: str = "evolution"
    source_task_ids: list[str] = field(default_factory=list)
    issue_type: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "EvolvedSkill":
        required = ("id", "title", "pattern", "tip")
        missing = [key for key in required if not data.get(key)]
        if missing:
            raise ValueError(f"Evolved skill missing required fields: {missing}")
        return cls(
            id=str(data["id"]),
            title=str(data["title"]),
            pattern=str(data["pattern"]),
            tip=str(data["tip"]),
            source=str(data.get("source") or "evolution"),
            source_task_ids=[str(tid) for tid in data.get("source_task_ids", [])],
            issue_type=data.get("issue_type"),
            metadata=dict(data.get("metadata") or {}),
        )

    def to_harness_skill(self):
        """Convert to ``ecdysis.harness.skills.Skill`` lazily to avoid import cycles."""
        from ecdysis.harness.skills import Skill

        numeric_task_ids: list[int] = []
        for task_id in self.source_task_ids:
            try:
                numeric_task_ids.append(int(task_id))
            except ValueError:
                continue

        return Skill(
            id=self.id,
            title=self.title,
            pattern=self.pattern,
            tip=self.tip,
            source="failure",
            task_ids=numeric_task_ids,
            issue_type=self.issue_type,
        )

    def to_tau2_skill(self):
        """Backward-compatible alias for older experiment code."""
        return self.to_harness_skill()


@dataclass
class SkillArtifact:
    """Versioned JSON document containing evolved H5 skills."""

    experiment: str
    domain: str
    round: int
    mode: ArtifactMode
    skills: list[EvolvedSkill] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    parent_artifacts: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    schema_version: int = 1

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SkillArtifact":
        for key in ("experiment", "domain", "round", "mode"):
            if key not in data:
                raise ValueError(f"Skill artifact missing required field: {key}")
        return cls(
            experiment=str(data["experiment"]),
            domain=str(data["domain"]),
            round=int(data["round"]),
            mode=data["mode"],
            skills=[EvolvedSkill.from_dict(s) for s in data.get("skills", [])],
            created_at=str(data.get("created_at") or datetime.now().isoformat()),
            parent_artifacts=[str(p) for p in data.get("parent_artifacts", [])],
            metadata=dict(data.get("metadata") or {}),
            schema_version=int(data.get("schema_version", 1)),
        )

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def validate_for_domain(self, domain: str) -> None:
        if self.domain != domain:
            raise ValueError(
                f"Artifact domain mismatch: expected {domain}, got {self.domain}"
            )


def load_skill_artifact(path: str | Path) -> SkillArtifact:
    artifact_path = Path(path)
    data = json.loads(artifact_path.read_text())
    artifact = SkillArtifact.from_dict(data)
    return artifact


def save_skill_artifact(artifact: SkillArtifact, path: str | Path) -> Path:
    artifact_path = Path(path)
    artifact_path.parent.mkdir(parents=True, exist_ok=True)
    artifact_path.write_text(json.dumps(artifact.to_dict(), indent=2))
    return artifact_path


def load_evolved_skills(paths: list[str | Path], domain: str | None = None):
    """Load evolved skills from one or more artifacts for H5 retrieval."""
    skills = []
    seen_ids: set[str] = set()
    for path in paths:
        artifact = load_skill_artifact(path)
        if domain is not None:
            artifact.validate_for_domain(domain)
        for skill in artifact.skills:
            if skill.id in seen_ids:
                continue
            seen_ids.add(skill.id)
            skills.append(skill.to_harness_skill())
    return skills


def merge_skill_artifacts(
    *,
    experiment: str,
    domain: str,
    round_num: int,
    mode: ArtifactMode,
    artifacts: list[SkillArtifact],
    new_skills: list[EvolvedSkill] | None = None,
    metadata: dict[str, Any] | None = None,
) -> SkillArtifact:
    """Merge parent artifacts and append new skills, deduplicating by id."""
    merged: list[EvolvedSkill] = []
    seen_ids: set[str] = set()
    parents: list[str] = []
    for artifact in artifacts:
        artifact.validate_for_domain(domain)
        parents.extend(artifact.parent_artifacts)
        for skill in artifact.skills:
            if skill.id in seen_ids:
                continue
            seen_ids.add(skill.id)
            merged.append(skill)
    for skill in new_skills or []:
        if skill.id in seen_ids:
            continue
        seen_ids.add(skill.id)
        merged.append(skill)

    return SkillArtifact(
        experiment=experiment,
        domain=domain,
        round=round_num,
        mode=mode,
        skills=merged,
        parent_artifacts=parents,
        metadata=metadata or {},
    )
